name: windows

on: [push, pull_request]

jobs:

  Build:
    name: ${{matrix.name}} (${{matrix.config}})
    runs-on: ${{matrix.os}}

    env:
      CMAKE_GENERATOR: Ninja

    strategy:
      fail-fast: false
      matrix:
        name: [
          windows-2019-msvc2019,
          windows-2019-msvc2019-win32,
          windows-2019-msvc2019-arm64,
          windows-2019-msvc2019-clang,
          windows-2022-msvc2022,
          windows-2022-msvc2022-win32,
          windows-2022-msvc2022-arm64,
          windows-2022-msvc2022-clang
        ]
        config: [Debug, Release]
        include:
          - name: windows-2019-msvc2019
            os: windows-2019
            compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
            version: Visual Studio 16 2019

          - name: windows-2019-msvc2019-win32
            os: windows-2019
            compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe
            version: Visual Studio 16 2019

          - name: windows-2019-msvc2019-arm64
            os: windows-2019
            compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/arm64/cl.exe
            version: Visual Studio 16 2019

          - name: windows-2019-msvc2019-clang
            os: windows-2019
            compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe
            version: Visual Studio 16 2019

          - name: windows-2022-msvc2022
            os: windows-2022
            compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
            version: Visual Studio 17 2022

          - name: windows-2022-msvc2022-win32
            os: windows-2022
            compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x86/cl.exe
            version: Visual Studio 17 2022

          - name: windows-2022-msvc2022-arm64
            os: windows-2022
            compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.34.31933/bin/Hostx64/arm64/cl.exe
            version: Visual Studio 17 2022

          - name: windows-2022-msvc2022-clang
            os: windows-2022
            compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/Llvm/x64/bin/clang-cl.exe
            version: Visual Studio 17 2022

    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: |
             choco install doxygen.install graphviz ninja -y

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake $env:GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE:STRING=${{matrix.config}} "-DCMAKE_C_COMPILTER:STRING=${{matrix.compiler}}" "-DCMAKE_CXX_COMPILTER:STRING=${{matrix.compiler}}"

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config ${{matrix.config}}

      - name: Test
        if: matrix.architecture != '-A ARM64'
        working-directory: ${{runner.workspace}}/build
        run: ctest --output-on-failure -C ${{matrix.config}}

      - name: Documentation
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target documentation
